import QtQuick
pragma Singleton

// Semantic color roles, derived from whatever WalColors.qml currently
// contains (regenerated by `wal` on every wallpaper change).
QtObject {
    id: root

    readonly property QtObject
    raw: WalColors {
    }

    // ---- Raw pass-through -----------------------------------------
    readonly property color color0: raw.color0
    readonly property color color1: raw.color1
    readonly property color color2: raw.color2
    readonly property color color3: raw.color3
    readonly property color color4: raw.color4
    readonly property color color5: raw.color5
    readonly property color color6: raw.color6
    readonly property color color7: raw.color7
    readonly property color color8: raw.color8
    readonly property color color9: raw.color9
    readonly property color color10: raw.color10
    readonly property color color11: raw.color11
    readonly property color color12: raw.color12
    readonly property color color13: raw.color13
    readonly property color color14: raw.color14
    readonly property color color15: raw.color15
    readonly property color cursor: raw.cursor
    // ---- Semantic roles (use these) --------------------------------
    readonly property color background: raw.background
    readonly property color foreground: raw.foreground
    readonly property color surface: Qt.lighter(raw.background, 1.15)
    readonly property color surfaceAlt: Qt.lighter(raw.background, 1.3)
    readonly property color muted: raw.color8
    // One computed accent — whichever of color1..color6 is most
    // saturated and closest to mid-brightness.
    readonly property color accent: _pickAccent()
    // A single softened version of that accent, for resting-state
    // icons that should look tinted rather than flat gray but not as
    // loud as the full accent (which is reserved for active/selected/
    // hover states).
    readonly property color accentMuted: Qt.tint(muted, Qt.rgba(accent.r, accent.g, accent.b, 0.45))
    readonly property color critical: "#e06c75"
    readonly property color success: "#98c379"

    function _pickAccent() {
        const candidates = [raw.color1, raw.color2, raw.color3, raw.color4, raw.color5, raw.color6];
        let best = raw.color4;
        let bestScore = -1;
        for (let i = 0; i < candidates.length; i++) {
            const c = candidates[i];
            const score = c.hsvSaturation * (1 - Math.abs(c.hsvValue - 0.65));
            if (score > bestScore) {
                bestScore = score;
                best = c;
            }
        }
        return best;
    }

}
