# RPC
enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800

# Downloads
dir=/home/licht/Downloads
max-concurrent-downloads=1
max-connection-per-server=16
min-split-size=1M
split=16
continue=true

# BitTorrent
enable-dht=true
enable-peer-exchange=true
bt-enable-lpd=true
seed-ratio=1.0
seed-time=30
follow-torrent=true
bt-save-metadata=true
