general {
    lock_cmd = pidof hyprlock || hyprlock   # avoid multiple instances
    before_sleep_cmd = loginctl lock-session # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false  # respect Firefox/Steam idle inhibit
}

# 4 min: dim screen warning
listener {
    timeout = 240
    on-timeout = notify-send "Locking in 1 minute..."
}

# 5 min: lock screen
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = notify-send "Welcome back!"
}

# 7 min: turn off display
listener {
    timeout = 420
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

