set -g status-style "bg={background},fg={foreground}"

set -g status-left-length 40
set -g status-left "#[bg={color4},fg={background},bold] #S #[bg={background},fg={color4}]"

set -g status-right-length 60
set -g status-right "#[fg={color8}]%Y-%m-%d #[fg={color4}]%H:%M "

set -g window-status-format " #I:#W "
set -g window-status-current-format "#[bg={color4},fg={background},bold] #I:#W "

set -g pane-border-style "fg={color8}"
set -g pane-active-border-style "fg={color4}"

set -g message-style "bg={color4},fg={background}"
